### ISSUE TITLE
Synchronise Reset output with Clock output

### ISSUE THREAD

**Issue by hotchk155** [hotchk155/matrix-seq-firmware2#11]
The reset output of Noodlebox does not reset the Transient Modules 8S. There seems to be a limitation on the 8S where the reset is only read on a clock pulse, so a clock pulse needs to be seen during the reset signal. 

[Romain Welker]

**Comment by hotchk155** [comment]
Actually looking like this is more of a bug, where a clock tick should be present along with the reset pulse.. 

What it is doing now is:
X____      reset out
_XXX      clock out

But what it should be doing is:
X____     reset out
XXXX      clock out

**Comment by hotchk155** [comment]
useful reference https://learningmodular.com/master-clocks-reset/

**Comment by hotchk155** [comment]
fixed in release 1.1

**Comment by hotchk155** [comment]
Reopen this issue following additional information from Romain Welker

**Comment by RomainWELKER** [comment]
So to be more precise, when using internal clock, the issue still exists in firmware 1.1 but only if the sequencer is stopped. If you manually reset the sequencer WHILE it's running, both the reset and the clock tick are output at the same time. However, the signals are output as soon as you reset the Noodlebox so it doesn't wait for the next clock tick to reset. It would be nice if it could wait for the next clock tick so the clock stays in sync.
